### ISSUE TITLE
Exceptions carry no __traceback__, so traceback.format_exc() can never report a frame

### ISSUE THREAD

**Issue by jgfoster** [GemTalk/Grail#849]
Exceptions carry no `__traceback__`, so `traceback` can never produce a frame.

`sys.exc_info()[2]` is `None` and `exc.__traceback__` is `None`, so every function in the
`traceback` module degrades to the exception's type and message on one line. There is no
`File "…", line N, in f` anywhere, and no way for a program to get one.

### Measured

Grail `5e8fc42`, engine 3.7.5, arm64.Darwin.

```python
import sys, traceback


def inner(form):
    return form.get("x")


def outer(form):
    return inner(form)


try:
    outer(5)
except Exception as exc:
    print(repr(exc.__traceback__))
    print(repr(sys.exc_info()))
    print(repr(traceback.format_exc()))
    print(repr(traceback.format_exception(type(exc), exc, exc.__traceback__)))
```

```
None
(<class 'AttributeError'>, AttributeError("'SmallInteger' object has no attribute 'get'"), None)
"AttributeError: 'SmallInteger' object has no attribute 'get'\n"
["AttributeError: 'SmallInteger' object has no attribute 'get'\n"]
```

Neither `outer` nor `inner` appears. CPython would report both frames with the offending
source line.

### Why it matters

The message alone is often not enough to locate the fault. `'SmallInteger' object has no
attribute 'get'` above is true of a call in `parse_answers`, but nothing says so, and in a
web app serving a dozen routes that is the difference between a thirty-second fix and an
afternoon. It also silently weakens anything that formats exceptions for a user: logging
handlers, test runners, and `raise ... from ...` chains all reduce to one line.

The information exists on the Smalltalk side — the GsProcess stack is available when the
exception is signalled — so this is about attaching it to the Python exception rather than
recovering something that was lost.

### Suggested fix

Populate `__traceback__` when a Python exception is raised, even coarsely: a chain of
frames carrying function name and the file and line the codegen already knows would make
`format_exc()` useful without needing full CPython fidelity. Partial frames would be a
large improvement over none.

Related: #848 — `sys.stdout`/`sys.stderr` are `None`, which separately breaks
`traceback.print_exc()` before it gets as far as having nothing to print.

**Comment by jgfoster** [comment]
Fixed by 83312c712dcae49fcf668fa48e970cd529f208f0 (PR #781, "traceback: `<module>` frames, and everything they were hiding", merged 2026-09-01) — six days before this was filed. The report was accurate for the commit it measured; `5e8fc42` predates the fix.

### Re-measured

Current `main` (`24fd1b42`), gs40, arm64.Darwin — the script from the report, unmodified:

```
<traceback object at 0x15017209>
(<class 'AttributeError'>, AttributeError("'SmallInteger' object has no attribute 'get'"), <traceback object at 0x15017209>)
```

`format_exc()` now returns all three frames with the source line and PEP 657 carets:

```
Traceback (most recent call last):
  File "repro849.py", line 13, in <module>
    outer(5)
    ~~~~~^^^
  File "repro849.py", line 9, in outer
    return inner(form)
  File "repro849.py", line 5, in inner
    return form.get("x")
           ^^^^^^^^
AttributeError: 'SmallInteger' object has no attribute 'get'
```

Diffed against CPython 3.14.6 on the same script, the output is byte-for-byte identical apart from the type name in the message (below).

### The fix is attributable, not incidental

I checked out the reported `5e8fc42` on gs40 and ran the same script, to rule out the engine being the variable — it reproduces exactly as filed:

```
None
(<class 'AttributeError'>, AttributeError("'SmallInteger' object has no attribute 'get'"), None)
```

So the defect was real on 4.0 too, and `git bisect` over the 842 commits since lands on 83312c71. That commit is a direct match for this report's shape: the exception here is caught at **module scope**, and the walk identified a Python frame by a `___curPos___` store that codegen emitted only inside functions. A module body was therefore not merely unnamed but invisible, so the catching frame was never pushed — which took the frames of every function the exception had passed through with it. That is why `outer` and `inner` were missing and not just `<module>`.

### Guarded

`tests/python/module_frames.py::a_module_scope_catch_has_frames` is this issue's shape (module-scope catch of a deeper call) and runs in the CI fixture gate, with `ModuleFrameTestCase` alongside it in the SUnit shards.

### One residual difference, not a traceback one

Grail says `'SmallInteger' object has no attribute 'get'` where CPython says `'int'`. That is the type name in the message, unrelated to `__traceback__` — every frame, line and caret matches. Not tracked anywhere that I can find; worth its own issue if it bites.
